import { Driver, Trip } from './types';

export const mockDrivers: Driver[] = [
  { id: '101', name: 'ישראל ישראלי', phone: '050-1234567', licensePlate: '12-345-67', busType: 'אוטובוס עירוני' },
  { id: '102', name: 'משה כהן', phone: '052-7654321', licensePlate: '98-765-43', busType: 'אוטובוס תיירותי' },
  { id: '103', name: 'דוד לוי', phone: '054-1112223', licensePlate: '55-444-33', busType: 'מיניבוס' },
];

export const mockTrips: Trip[] = [
  {
    id: 't1',
    driverId: '101',
    date: '2026-03-20',
    time: '08:00',
    destination: 'ירושלים',
    route: 'כביש 1',
    stops: ['תל אביב', 'מחלף חמד', 'ירושלים'],
    busId: '12-345-67',
    departureStation: 'תחנה מרכזית תל אביב',
    status: 'scheduled',
  },
  {
    id: 't2',
    driverId: '102',
    date: '2026-03-20',
    time: '10:30',
    destination: 'חיפה',
    route: 'כביש 2',
    stops: ['נתניה', 'חדרה', 'חיפה'],
    busId: '98-765-43',
    departureStation: 'מסוף רידינג',
    status: 'scheduled',
  },
  {
    id: 't3',
    driverId: '101',
    date: '2026-03-21',
    time: '07:00',
    destination: 'אילת',
    route: 'כביש 90',
    stops: ['באר שבע', 'דימונה', 'אילת'],
    busId: '12-345-67',
    departureStation: 'תחנה מרכזית תל אביב',
    status: 'scheduled',
  },
  {
    id: 't4',
    driverId: '103',
    date: '2026-03-20',
    time: '08:00',
    destination: 'טבריה',
    route: 'כביש 6',
    stops: ['עפולה', 'צומת גולני', 'טבריה'],
    busId: '55-444-33',
    departureStation: 'תחנה מרכזית חיפה',
    status: 'scheduled',
  },
  {
    id: 't5',
    driverId: '102',
    date: '2026-03-21',
    time: '07:00',
    destination: 'צפת',
    route: 'כביש 85',
    stops: ['כרמיאל', 'צומת עמיעד', 'צפת'],
    busId: '98-765-43',
    departureStation: 'תחנה מרכזית תל אביב',
    status: 'scheduled',
  },
  // Historical Data - Last 6 Months
  {
    id: 'h1',
    driverId: '101',
    date: '2025-09-15',
    time: '08:00',
    destination: 'ירושלים',
    route: 'כביש 1',
    stops: ['תל אביב', 'ירושלים'],
    busId: '12-345-67',
    departureStation: 'תחנה מרכזית תל אביב',
    status: 'scheduled',
  },
  {
    id: 'h2',
    driverId: '101',
    date: '2025-10-05',
    time: '09:00',
    destination: 'חיפה',
    route: 'כביש 2',
    stops: ['תל אביב', 'חיפה'],
    busId: '12-345-67',
    departureStation: 'תחנה מרכזית תל אביב',
    status: 'scheduled',
  },
  {
    id: 'h3',
    driverId: '101',
    date: '2025-10-20',
    time: '10:00',
    destination: 'באר שבע',
    route: 'כביש 40',
    stops: ['תל אביב', 'באר שבע'],
    busId: '12-345-67',
    departureStation: 'תחנה מרכזית תל אביב',
    status: 'cancelled',
  },
  {
    id: 'h4',
    driverId: '102',
    date: '2025-11-12',
    time: '07:30',
    destination: 'אילת',
    route: 'כביש 90',
    stops: ['תל אביב', 'אילת'],
    busId: '98-765-43',
    departureStation: 'תחנה מרכזית תל אביב',
    status: 'scheduled',
  },
  {
    id: 'h5',
    driverId: '102',
    date: '2025-12-01',
    time: '08:00',
    destination: 'טבריה',
    route: 'כביש 6',
    stops: ['תל אביב', 'טבריה'],
    busId: '98-765-43',
    departureStation: 'תחנה מרכזית תל אביב',
    status: 'scheduled',
  },
  {
    id: 'h6',
    driverId: '103',
    date: '2025-12-15',
    time: '09:00',
    destination: 'צפת',
    route: 'כביש 85',
    stops: ['חיפה', 'צפת'],
    busId: '55-444-33',
    departureStation: 'תחנה מרכזית חיפה',
    status: 'scheduled',
  },
  {
    id: 'h7',
    driverId: '101',
    date: '2026-01-10',
    time: '08:30',
    destination: 'נהריה',
    route: 'כביש 4',
    stops: ['תל אביב', 'נהריה'],
    busId: '12-345-67',
    departureStation: 'תחנה מרכזית תל אביב',
    status: 'scheduled',
  },
  {
    id: 'h8',
    driverId: '102',
    date: '2026-01-22',
    time: '11:00',
    destination: 'אשדוד',
    route: 'כביש 4',
    stops: ['תל אביב', 'אשדוד'],
    busId: '98-765-43',
    departureStation: 'תחנה מרכזית תל אביב',
    status: 'cancelled',
  },
  {
    id: 'h9',
    driverId: '103',
    date: '2026-02-05',
    time: '07:00',
    destination: 'כרמיאל',
    route: 'כביש 70',
    stops: ['חיפה', 'כרמיאל'],
    busId: '55-444-33',
    departureStation: 'תחנה מרכזית חיפה',
    status: 'scheduled',
  },
  {
    id: 'h10',
    driverId: '101',
    date: '2026-02-18',
    time: '14:00',
    destination: 'קרית שמונה',
    route: 'כביש 90',
    stops: ['תל אביב', 'קרית שמונה'],
    busId: '12-345-67',
    departureStation: 'תחנה מרכזית תל אביב',
    status: 'scheduled',
  },
  {
    id: 'h11',
    driverId: '103',
    date: '2025-09-28',
    time: '10:00',
    destination: 'נתניה',
    route: 'כביש 2',
    stops: ['חיפה', 'נתניה'],
    busId: '55-444-33',
    departureStation: 'תחנה מרכזית חיפה',
    status: 'scheduled',
  },
  {
    id: 'h12',
    driverId: '102',
    date: '2025-10-15',
    time: '08:00',
    destination: 'רחובות',
    route: 'כביש 40',
    stops: ['תל אביב', 'רחובות'],
    busId: '98-765-43',
    departureStation: 'תחנה מרכזית תל אביב',
    status: 'scheduled',
  },
];
