CREATE TABLE BUS
(
  BusID INT NOT NULL,
  LicensePlate INT NOT NULL,
  Capacity INT NOT NULL,
  Manufacturer VARCHAR(50) NOT NULL,
  Model VARCHAR(20) NOT NULL,
  Year INT NOT NULL,
  PRIMARY KEY (BusID)
);

CREATE TABLE ROUTE
(
  RouteID INT NOT NULL,
  RouteName VARCHAR(50) NOT NULL,
  StartLocation VARCHAR(50) NOT NULL,
  EndLocation VARCHAR(50) NOT NULL,
  EstimatedDuration INT NOT NULL,
  PRIMARY KEY (RouteID)
);

CREATE TABLE STOP
(
  StopID INT NOT NULL,
  StopName VARCHAR(100) NOT NULL,
  Address VARCHAR(100) NOT NULL,
  Latitude DECIMAL(10, 6) NOT NULL,
  Longitude DECIMAL(10, 6) NOT NULL,
  PRIMARY KEY (StopID)
);

CREATE TABLE DRIVER
(
  DriverID INT NOT NULL,
  FullName VARCHAR(100) NOT NULL,
  LicenseType VARCHAR(10) NOT NULL,
  PRIMARY KEY (DriverID)
);

CREATE TABLE ROUTESTOP
(
  StopOrder INT NOT NULL,
  RouteID INT NOT NULL,
  StopID INT NOT NULL,
  PRIMARY KEY (RouteID, StopID),
  FOREIGN KEY (RouteID) REFERENCES ROUTE(RouteID),
  FOREIGN KEY (StopID) REFERENCES STOP(StopID)
);

CREATE TABLE TRIP
(
  TripID INT NOT NULL,
  DriverID INT NOT NULL,
  RouteID INT NOT NULL,
  BusID INT NOT NULL,
  PRIMARY KEY (TripID),
  FOREIGN KEY (DriverID) REFERENCES DRIVER(DriverID),
  FOREIGN KEY (RouteID) REFERENCES ROUTE(RouteID),
  FOREIGN KEY (BusID) REFERENCES BUS(BusID)
);