INSERT INTO bus (busid, licenseplate, capacity, manufacturer, model, year) VALUES
(2001, 102001, 26, 'Mercedes', 'M1', 2011);

INSERT INTO driver (driverid, fullname, licensetype) VALUES
(2001, 'Alexander Ross', 'A');

INSERT INTO route (routeid, routename, startlocation, endlocation, estimatedduration) VALUES
(1001, 'Synergized global Local Area Network', 'Kyleville Dep', 'Susanchester Arr', 57),
(1002, 'Distributed contextually-based Graphic Interface', 'East Davidberg Dep', 'Torresborough Arr', 58),
(1003, 'Ergonomic human-resource conglomeration', 'Joshuaberg Dep', 'South Karen Arr', 59),
(1004, 'Decentralized empowering middleware', 'South Melissaberg Dep', 'North Eddieburgh Arr', 60),
(1005, 'Pre-emptive responsive archive', 'South Joseph Dep', 'Riveraport Arr', 61),
(1006, 'Future-proofed systematic monitoring', 'Lake Timothy Dep', 'New Gregory Arr', 62),
(1007, 'Future-proofed attitude-oriented focus group', 'Danielton Dep', 'New Melissashire Arr', 63),
(1008, 'Progressive 4thgeneration standardization', 'South Alejandramouth Dep', 'Padillatown Arr', 64),
(1009, 'Persistent executive budgetary management', 'East Thomas Dep', 'Michaelside Arr', 65),
(1010, 'Automated 6thgeneration secured line', 'Reedside Dep', 'Mcmillanborough Arr', 66),
(1011, 'Universal 24/7 contingency', 'Port Mary Dep', 'East Taylor Arr', 67),
(1012, 'Advanced 6thgeneration access', 'New Aaron Dep', 'New David Arr', 68),
(1013, 'Extended multimedia open system', 'Haroldbury Dep', 'Amyside Arr', 69),
(1014, 'Visionary discrete core', 'New Derekside Dep', 'Longview Arr', 70),
(1015, 'Persistent national implementation', 'South Donald Dep', 'Brianview Arr', 71),
(1016, 'User-centric global open system', 'Jasonmouth Dep', 'Solomonberg Arr', 72),
(1017, 'Public-key methodical strategy', 'Lake Joseph Dep', 'New Sharon Arr', 73),
(1018, 'Reactive executive success', 'Perezside Dep', 'South Crystalberg Arr', 74),
(1019, 'Open-source local framework', 'Solisport Dep', 'Port Nathaniel Arr', 75),
(1020, 'Re-engineered optimal pricing structure', 'Lake Michelle Dep', 'Tuckerland Arr', 76),
(1021, 'User-friendly object-oriented matrices', 'New Gerald Dep', 'North Peter Arr', 77),
(1022, 'Innovative attitude-oriented hub', 'North Shannon Dep', 'Stevenmouth Arr', 78),
(1023, 'Team-oriented background info-mediaries', 'Marktown Dep', 'West Scottbury Arr', 79),
(1024, 'Right-sized tangible system engine', 'North Susan Dep', 'Munozton Arr', 80),
(1025, 'Enhanced secondary policy', 'Rodgershaven Dep', 'Courtneyburgh Arr', 81),
(1026, 'Extended client-driven orchestration', 'Port Francisco Dep', 'Carpenterstad Arr', 82),
(1027, 'Open-source discrete attitude', 'South Karenville Dep', 'East Scott Arr', 83),
(1028, 'Persistent maximized model', 'Alanmouth Dep', 'Morganbury Arr', 84),
(1029, 'Open-source client-driven process improvement', 'Lake Jenniferberg Dep', 'East Derekfort Arr', 85),
(1030, 'Multi-channeled 24/7 collaboration', 'New Jenniferton Dep', 'Adrianmouth Arr', 86),
(1031, 'Cloned systematic encoding', 'Patriciafurt Dep', 'Port Stephaniechester Arr', 87),
(1032, 'De-engineered clear-thinking open architecture', 'Danielbury Dep', 'Lake Daniel Arr', 88),
(1033, 'Re-contextualized explicit focus group', 'Patelview Dep', 'Faithview Arr', 89),
(1034, 'Total user-facing challenge', 'Nelsonburgh Dep', 'Gomezview Arr', 90),
(1035, 'Secured exuding Graphic Interface', 'West David Dep', 'Wilsonmouth Arr', 91),
(1036, 'Streamlined bifurcated pricing structure', 'Alexisshire Dep', 'Davidfurt Arr', 92),
(1037, 'Multi-tiered bifurcated success', 'Ariasview Dep', 'East Nataliefurt Arr', 93),
(1038, 'Robust 3rdgeneration artificial intelligence', 'Lake Matthew Dep', 'Jenniferburgh Arr', 94),
(1039, 'Digitized tertiary standardization', 'East Anthonyville Dep', 'East Christopherfurt Arr', 95),
(1040, 'Devolved explicit moratorium', 'Allenland Dep', 'Robertshire Arr', 96),
(1041, 'Operative tangible Graphic Interface', 'Cynthiamouth Dep', 'Mitchellbury Arr', 97),
(1042, 'Self-enabling object-oriented initiative', 'North Kennethbury Dep', 'Port Michellestad Arr', 98),
(1043, 'Switchable exuding circuit', 'Gregoryberg Dep', 'North Justin Arr', 99),
(1044, 'Operative cohesive knowledgebase', 'Port Andrewberg Dep', 'North Bradleybury Arr', 100),
(1045, 'Self-enabling intermediate collaboration', 'Lake Tonya Dep', 'Thomasborough Arr', 101),
(1046, 'Customizable next generation algorithm', 'Port Heather Dep', 'Bergfurt Arr', 102),
(1047, 'Cloned eco-centric support', 'Lake Rubenburgh Dep', 'Espinozahaven Arr', 103),
(1048, 'Team-oriented zero administration success', 'North Erikaborough Dep', 'Port Teresaberg Arr', 104),
(1049, 'Enterprise-wide full-range complexity', 'Donnaberg Dep', 'Port Alejandro Arr', 105),
(1050, 'User-centric demand-driven access', 'Wrighttown Dep', 'Williamsmouth Arr', 106),
(1051, 'Multi-channeled empowering algorithm', 'Howardberg Dep', 'Mcclureshire Arr', 107),
(1052, 'Switchable holistic implementation', 'Perryberg Dep', 'Port Sandyside Arr', 108),
(1053, 'Team-oriented national standardization', 'South Christopher Dep', 'Patelborough Arr', 109),
(1054, 'Reduced coherent structure', 'Norrisport Dep', 'Michellehaven Arr', 110),
(1055, 'Down-sized leadingedge artificial intelligence', 'Port Michaelberg Dep', 'Rickyshire Arr', 111),
(1056, 'Versatile explicit challenge', 'East Jeremy Dep', 'Javiermouth Arr', 112),
(1057, 'User-centric asymmetric moderator', 'Pagebury Dep', 'Bushport Arr', 113),
(1058, 'Re-engineered systematic architecture', 'Lucasview Dep', 'Tannerside Arr', 114),
(1059, 'Ergonomic well-modulated approach', 'East Christopher Dep', 'Lake Amanda Arr', 115),
(1060, 'Devolved impactful challenge', 'New Nicole Dep', 'Lake Jessicaport Arr', 116),
(1061, 'Visionary even-keeled implementation', 'West Devintown Dep', 'West Juanburgh Arr', 117),
(1062, 'Assimilated coherent task-force', 'Port Michelleborough Dep', 'Port Robert Arr', 118),
(1063, 'Face-to-face context-sensitive pricing structure', 'South Kennethview Dep', 'New Michaelside Arr', 119),
(1064, 'Automated optimal solution', 'East Howardton Dep', 'North Benjaminmouth Arr', 120),
(1065, 'Expanded multi-tasking system engine', 'Allenhaven Dep', 'Jessicatown Arr', 121),
(1066, 'Stand-alone multi-state emulation', 'South Larryburgh Dep', 'East Brendamouth Arr', 122),
(1067, 'Open-architected mobile collaboration', 'Allenshire Dep', 'Ryanstad Arr', 123),
(1068, 'Total full-range budgetary management', 'Lindseyberg Dep', 'Myersside Arr', 124),
(1069, 'Digitized content-based strategy', 'Stevenshire Dep', 'East Susan Arr', 125),
(1070, 'Enhanced background hardware', 'Lake Charlotte Dep', 'North Charlesstad Arr', 126),
(1071, 'Grass-roots upward-trending throughput', 'Port Sergioville Dep', 'New Ashleyberg Arr', 127),
(1072, 'Cloned context-sensitive encoding', 'Port Jonathanview Dep', 'Wilsonport Arr', 128),
(1073, 'Cross-platform coherent info-mediaries', 'South Michaeltown Dep', 'Davidmouth Arr', 129),
(1074, 'Upgradable secondary access', 'New Amanda Dep', 'Jonesview Arr', 130),
(1075, 'Synergized didactic initiative', 'Aprilbury Dep', 'East Josephside Arr', 131),
(1076, 'Versatile neutral website', 'North Leslie Dep', 'Terryfort Arr', 132),
(1077, 'Stand-alone zero administration algorithm', 'Stevenstad Dep', 'Jeremyborough Arr', 133),
(1078, 'Optional zero administration task-force', 'Jessicaport Dep', 'South Jacqueline Arr', 134),
(1079, 'Multi-tiered composite capacity', 'Lake Micheleburgh Dep', 'Peterport Arr', 135),
(1080, 'Customizable responsive system engine', 'North Danieltown Dep', 'Fergusonmouth Arr', 16),
(1081, 'Profit-focused zero-defect customer loyalty', 'North Michelle Dep', 'East Tammymouth Arr', 17),
(1082, 'Robust intangible algorithm', 'Lake Jeremiah Dep', 'Davisbury Arr', 18),
(1083, 'Devolved executive knowledge user', 'East Valerieside Dep', 'New Spencer Arr', 19),
(1084, 'Triple-buffered dedicated portal', 'West Kevinfurt Dep', 'Justinport Arr', 20),
(1085, 'Assimilated impactful standardization', 'Jessicamouth Dep', 'Lake Erika Arr', 21),
(1086, 'Ergonomic grid-enabled portal', 'Jasminefurt Dep', 'Lake Sydneyville Arr', 22),
(1087, 'Mandatory attitude-oriented success', 'New Nancy Dep', 'South Jennaport Arr', 23),
(1088, 'Public-key secondary algorithm', 'South Nicholas Dep', 'Toddmouth Arr', 24),
(1089, 'Robust high-level open system', 'Gonzalezmouth Dep', 'Gutierrezport Arr', 25),
(1090, 'Proactive reciprocal encoding', 'Kingport Dep', 'South Deborah Arr', 26),
(1091, 'Managed bi-directional Graphic Interface', 'Lake Christophermouth Dep', 'Andrewton Arr', 27),
(1092, 'Secured homogeneous installation', 'Ayalaview Dep', 'Port Dianabury Arr', 28),
(1093, 'Function-based bottom-line infrastructure', 'Lake Terry Dep', 'Lake Stephanieburgh Arr', 29),
(1094, 'Advanced cohesive moratorium', 'Perrychester Dep', 'Port Carlos Arr', 30),
(1095, 'Vision-oriented analyzing orchestration', 'New Meganborough Dep', 'Port Margaret Arr', 31),
(1096, 'Exclusive foreground alliance', 'Moralesshire Dep', 'South Juan Arr', 32),
(1097, 'Customer-focused multi-state attitude', 'North Katherine Dep', 'Williamsmouth Arr', 33),
(1098, 'Mandatory fault-tolerant paradigm', 'New Aaronville Dep', 'Taramouth Arr', 34),
(1099, 'Front-line actuating system engine', 'Aliciamouth Dep', 'Nelsonmouth Arr', 35),
(1100, 'Re-engineered grid-enabled solution', 'East Staceyside Dep', 'Port Paulland Arr', 36);

INSERT INTO stop (stopid, stopname, address, latitude, longitude) VALUES
(2001, 'Diaz Plain Stop', '30197 Watts Alley Suite 694, North Jamie, IA 47103', 32.08, 34.78);

INSERT INTO routestop (stoporder, routeid, stopid) VALUES
(1, 2001, 2001);

INSERT INTO trip (tripid, driverid, routeid, busid) VALUES
(2001, 2001, 2001, 2001);